export const UPDATE_CONTEXT_FORM = 'UPDATE_CONTEXT_FORM';
export const FETCH_INFORMATION_REQUESTED = 'FETCH_INFORMATION_REQUESTED';
export const SUBMIT_INFORMATION_REQUESTED = 'SUBMIT_INFORMATION_REQUESTED';
